### ISSUE TITLE
What is VTKPost

### ISSUE THREAD

**Issue by richb2k** [ElmerCSC/elmerfem-manuals#4]
Hello,

In the file, TempDist.tex, line 242, reads as follows:

_were generated by the obsolete VTKPost tool within ElmerGUI_

Should this actually be written in the manual as 'ElmerPost', instead of VTKPost?

I understand that ElmerPost is deprecated and will  be removed at some point.  

There is a note in the file, GuiInstructions.tex, line 34:

_that as of ElmerGUI v 9.0, the VTK widget has been upgraded to read .vtu files._

Is the VTK widget going to be deprecated in the future, or will it be around for a while?  

Thanks,  Rich B

**Comment by raback** [comment]
Great question. ElmerPost is the original postprocessing tool for the Elmer project. It was completely in-house written in Tcl/Tk with its own .ep format. Unfortunately time has passed it. However, ElmerGUI also includes a postprocessing tool based on VTK library. Before it used to read the .ep format which was motivated by the fact that then we could smoothly transition between ElmerPost and VTKPost. For some time we thought that both of these would die with .ep format giving way to the .vtu format. However, thanx to the great work by Saeki in the true open source spirit the VTK widget (aka VTKPost) within ElmerGUI now can read .vtu files, and also we can compile it with QT5. So this means that VTKPost is not obsolite. However, it has nothing over Paraview so the main possible reason to favour it is the cohesion and ease of use of the integrated tool when compared to all bells-and-whisles Paraview. So I would use it for 5-minute demo, but not for 2-day course. But at the moment we don't have any plans to eliminate it. Saeki has given it continued life.

**Comment by richb2k** [comment]
Thanks, that helps a lot.  ElmerVTK was easy to use, particularly with the first beginning tutorial.  It took me awhile to figure out how to get Paraview to show the results, but then it worked nicely.  I see in the forum that many beginners have the same issue, having trouble to get Paraview to show results.  How would it be if I made a 'Getting Started' chapter that would be in the manual before the first tutorial?  Something like 'GuiInstructions.tex', but with more steps to help a beginner?
